name: Fetch Zotero Items Daily

on:
  schedule:
    - cron: '0 2 * * *'  # Every day at 2 AM UTC
  workflow_dispatch:     # Manual trigger option

permissions:
  contents: write  # ✅ allow committing to repo

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyzotero

      - name: Run fetch script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
        run: |
          python fetch_zotero.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add zotero_items.json         # ✅ match the filename you generate
          git commit -m "Update Zotero items [auto]" || echo "No changes to commit"
          git push
